@base_url = https://localhost:7015/api/tarefa

### Listar Tarefas ###
GET {{base_url}}/listar

### Criar Tarefa ###
POST {{base_url}}/cadastrar
Content-Type: application/json

{
  "Titulo": "Compras no Supermercado",
  "Descricao": "1. Fazer lista de compras: pão, leite, ovos, frutas, vegetais",
  "CategoriaId": 2
}

### Alterar Tarefa ###
PUT {{base_url}}/alterar/16
Content-Type: application/json

{
    "Status": "",
    "CategoiraId": 2
}

### Listar Tarefa concluidas ###

GET {{base_url}}/concluidas


### Listar Tarefas não concluidas ###

GET {{base_url}}/naoconcluidas
